# Generated by Django 5.2.4 on 2025-07-22 09:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ma_khach_hang', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('ten_khach_hang', models.CharField(max_length=100)),
                ('dia_chi', models.TextField()),
                ('so_dien_thoai', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('ma_hoa_don', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('ngay_lap_hoa_don', models.DateField()),
                ('trang_thai', models.CharField(max_length=20)),
                ('tong_tien', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('ma_loai', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('ten_loai', models.CharField(max_length=100)),
                ('gia_phong', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ma_dich_vu', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('ten_dich_vu', models.CharField(max_length=100)),
                ('gia_dich_vu', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('ma_nhan_vien', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=100)),
                ('ngay_sinh', models.DateField()),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('ma_phong', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('so_phong', models.CharField(editable=False, max_length=10)),
                ('trang_thai', models.CharField(max_length=20)),
                ('ma_loai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='app.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceUsage',
            fields=[
                ('ma_sddv', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('so_luong', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ngay_su_dung', models.DateField()),
                ('status', models.CharField(choices=[('Chưa thanh toán', 'Unpaid'), ('Đã thanh toán', 'Paid')], default='Chưa thanh toán', max_length=20)),
                ('hoa_don', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_usages', to='app.invoice')),
                ('ma_dich_vu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_usages', to='app.service')),
                ('ma_khach_hang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_usages', to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ma_nhan_vien', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('ma_thue', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('ngay_thue', models.DateField()),
                ('ngay_nhan', models.DateField()),
                ('ngay_tra', models.DateField()),
                ('trang_thai', models.CharField(choices=[('Đã đặt', 'order'), ('Đang ở', 'using'), ('Đã trả', 'returned')], max_length=20)),
                ('hoa_don', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rents', to='app.invoice')),
                ('ma_khach_hang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rents', to='app.customer')),
                ('ma_phong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rents', to='app.room')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ma_thue', 'ma_khach_hang', 'ma_phong'), name='unique_rent_customer_room')],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('ma_loai', 'ma_phong'), name='unique_room_type_and_code'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='unique_username_email'),
        ),
    ]
