# Generated by Django 5.2.4 on 2025-07-15 06:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ma_khach_hang', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('ten_khach_hang', models.CharField(max_length=100)),
                ('dia_chi', models.TextField()),
                ('so_dien_thoai', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ma_phong', models.CharField(editable=False, max_length=14)),
                ('so_phong', models.CharField(max_length=10, unique=True)),
                ('trang_thai', models.CharField(choices=[('empty', 'Trống'), ('using', 'Đang sử dụng')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('ma_loai', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ten_loai', models.CharField(max_length=100)),
                ('gia_phong', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ma_dich_vu', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ten_dich_vu', models.CharField(max_length=100)),
                ('gia_dich_vu', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('ma_nhan_vien', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=100)),
                ('ngay_sinh', models.DateField()),
                ('so_dien_thoai', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ma_thue', models.UUIDField(editable=False)),
                ('ngay_thue', models.DateField()),
                ('ngay_nhan', models.DateField()),
                ('ngay_tra', models.DateField()),
                ('trang_thai', models.CharField(choices=[('order', 'Đã đặt'), ('using', 'Đang ở'), ('returned', 'Đã trả')], max_length=20)),
                ('ma_khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='app.customer')),
                ('ma_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='app.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='ma_loai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='app.roomtype'),
        ),
        migrations.CreateModel(
            name='ServiceUsage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ma_sddv', models.UUIDField(editable=False)),
                ('so_luong', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ngay_su_dung', models.DateField()),
                ('ma_dich_vu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_usages', to='app.service')),
                ('ma_thue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_usages', to='app.rent')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('ma_hoa_don', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ngay_lap_hoa_don', models.DateField()),
                ('tong_tien', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('ma_sddv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='app.serviceusage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rent',
            constraint=models.UniqueConstraint(fields=('ma_thue', 'ma_khach_hang', 'ma_phong'), name='unique_rent_customer_room'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('ma_loai', 'ma_phong'), name='unique_room_type_and_code'),
        ),
        migrations.AddConstraint(
            model_name='serviceusage',
            constraint=models.UniqueConstraint(fields=('ma_sddv', 'ma_thue', 'ma_dich_vu'), name='unique_service_usage'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('ma_hoa_don', 'ma_sddv'), name='unique_invoice_service_usage'),
        ),
    ]
