# Generated by Django 5.2.4 on 2025-07-23 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ma_nhan_vien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='app.staff'),
        ),
        migrations.AddField(
            model_name='rent',
            name='ma_nhan_vien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rents', to='app.staff'),
        ),
    ]
