# Generated by Django 5.2.4 on 2025-07-23 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_invoice_ma_nhan_vien_rent_ma_nhan_vien'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceusage',
            name='ma_nhan_vien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_usages', to='app.staff'),
        ),
    ]
